Website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/urls.py
from django.urls import path
from . import views
from schedule.views import Join, sched_delete

app_name = 'RAD'

urlpatterns = [
    path('', views.index, name='index'),
    path('experience/', views.experience, name='experience'),
    path('education/', views.education, name='education'),
    path('skills/', views.skills, name='skills'),
    path('contact/', views.contact, name='contact'),
    path('portofolio/', views.portofolio, name='portofolio'),    
    path('schedule/', Join, name = 'Schedule'),
    path('<int:pk>',sched_delete, name = 'Delete'),
]

homepage/models.py
from django.db import models

# Create your models here.

schedule/models.py
from django.db import models

class Schedule(models.Model):
    Day = models.CharField(max_length=30)
    Date = models.DateField(blank = False)
    Time = models.TimeField(blank = False)
    Name = models.TextField(max_length=50)
    Location = models.TextField(max_length=30)
    Category = models.TextField(max_length=30)

def __str__(self):
	return self.Name

schedule/forms.py
from django import forms
from . import models

class CreateSchedule(forms.Form):
    Day = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Day',
        'type' : 'text',
        'required': True,
    }))

    Date = forms.DateField(widget=forms.DateInput(attrs={
        'class': 'form-control',
        'placeholder' : 'dd/mm/yyyy',
        'type' : 'date',
        'required': True,
    }))

    Time = forms.TimeField(widget=forms.TimeInput(attrs={
        'class': 'form-control',
        'type' : 'time',
        'required': True,
    }))

    Name = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Activity Name',
        'required': True,
    }))

    Location = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Activity Location',
        'required': True,
    }))

    Category = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'type' : 'text',
        'placeholder': 'Activity Type',
        'required': True,
    }))

homepage/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

def experience(request):
    return render(request, 'experience.html')

def education(request):
    return render(request, 'education.html')

def skills(request):
    return render(request, 'skills.html')

def contact(request):
    return render(request, 'contact.html')

def portofolio(request):
    return render(request, 'portofolio.html')

schedule/views.py
from django.shortcuts import render, redirect
from . import forms
from .models import Schedule as jadwal
from .forms import CreateSchedule

def Join(request):
    if request.method == "POST":
        form = CreateSchedule(request.POST)
        if form.is_valid():
            sched = jadwal()
            sched.Day = form.cleaned_data['Day']
            sched.Date = form.cleaned_data['Date']
            sched.Time = form.cleaned_data['Time']
            sched.Name = form.cleaned_data['Name']
            sched.Location = form.cleaned_data['Location']
            sched.Category = form.cleaned_data['Category']
            sched.save()
        return redirect('/schedule')
    else:
        sched = jadwal.objects.all()
        form = CreateSchedule()
        response = {"sched":sched, 'form' : form}
        return render(request,'schedule.html',response)

def sched_delete(request, pk):
    if request.method == "POST":
        form = CreateSchedule(request.POST or None)
        if form.is_valid():
            sched = jadwal()
            sched.Day = form.cleaned_data['Day']
            sched.Date = form.cleaned_data['Date']
            sched.Time = form.cleaned_data['Time']
            sched.Name = form.cleaned_data['Name']
            sched.Location = form.cleaned_data['Location']
            sched.Category = form.cleaned_data['Category']
            sched.save()
        return redirect('/schedule')
    else:
        jadwal.objects.filter(pk=pk).delete()
        data = jadwal.objects.all()
        form = CreateSchedule()
        response = {"sched":data, 'form' : form}
        return render(request, 'schedule.html', response)

homepage/templates/contact.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/design.css' %}">

    <title>RAD</title>
  </head>
  <body class="mt-5">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
      <a class="navbar-brand" href="index.html">Raul Arrafi Delfarra</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'RAD:index' %}">About</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:experience' %}">Experience</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:education' %}">Education</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:skills' %}">Skills</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:contact' %}">Contact</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:Schedule' %}">Schedule</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:portofolio' %}">Portofolio</a>
        </div>
      </div>
      </div>
    </nav>

<section id="contact" class="ganjil">
<div class="container-fluid">
  <div class="row">
    <div class="col text-center">
      <h2>Contact</h2>
    </div>
  </div>

  <div class="row">
    <div class="col text-center">
      <i class="fa fa-facebook"></i>
      <h5>Raul Arrafi Delfarra</h5>
    </div>
  </div>

  <div class="row">
    <div class="col text-center">
      <i class="fa fa-instagram"></i>
      <h5>@raularrafi</h5>
    </div>
  </div>

  <div class="row">
    <div class="col text-center">
      <i class="fa fa-linkedin"></i>
      <h5>Raul Arrafi Delfarra</h5>
    </div>
  </div>
</div>
</section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/education.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/design.css' %}">

    <title>RAD</title>
  </head>
  <body class="mt-5">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
      <a class="navbar-brand" href="index.html">Raul Arrafi Delfarra</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'RAD:index' %}">About</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:experience' %}">Experience</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:education' %}">Education</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:skills' %}">Skills</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:contact' %}">Contact</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:Schedule' %}">Schedule</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:portofolio' %}">Portofolio</a>
        </div>
      </div>
      </div>
    </nav>

<section id="experience" class="genap">
<div class="container">
  <div class="row">
    <div class="col text-center"> 
      <h2>Education</h2>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <ul class="timeline">
          <li>
            <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Universitas Indonesia</h4>
              </div>
              <div class="timeline-body">
                <p>2018-Present</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge warning"><i class="glyphicon glyphicon-credit-card"></i></div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">SMAT Krida Nusantara Bandung</h4>
              </div>
              <div class="timeline-body">
                <p>2013-2016</p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-badge info"><i class="glyphicon glyphicon-floppy-disk"></i></div>
          </li>
          <li>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">SMPN 102 Jakarta</h4>
              </div>
              <div class="timeline-body">
                <p>2010-2013</p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge success"><i class="glyphicon glyphicon-thumbs-up"></i></div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">SDSN 03 Cijantung</h4>
              </div>
              <div class="timeline-body">
                <p>2009-2010</p>
              </div>
            </div>
          </li>
      </ul>
  </div>
  </div>
</div>
</section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/experience.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/design.css' %}">

    <title>RAD</title>
  </head>
  <body class="mt-5">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
      <a class="navbar-brand" href="index.html">Raul Arrafi Delfarra</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'RAD:index' %}">About</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:experience' %}">Experience</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:education' %}">Education</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:skills' %}">Skills</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:contact' %}">Contact</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:Schedule' %}">Schedule</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:portofolio' %}">Portofolio</a>
        </div>
      </div>
      </div>
    </nav>

<section id="experience" class="genap">
<div class="container-fluid">
  <div class="row">
    <div class="col text-center"> 
      <h2>Experience</h2>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <ul class="timeline">
          <li>
            <div class="timeline-badge"><i class="glyphicon glyphicon-check"></i></div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Wisuda Genap Fasilkom UI</h4>
              </div>
              <div class="timeline-body">
                <p></p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge warning"><i class="glyphicon glyphicon-credit-card"></i></div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">BEM Fasilkom UI</h4>
              </div>
              <div class="timeline-body">
                <p></p>
              </div>
            </div>
          </li>
          <li>
            <div class="timeline-badge info"><i class="glyphicon glyphicon-floppy-disk"></i></div>
          </li>
          <li>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Computers Get Together</h4>
              </div>
              <div class="timeline-body">
                <p></p>
              </div>
            </div>
          </li>
          <li class="timeline-inverted">
            <div class="timeline-badge success"><i class="glyphicon glyphicon-thumbs-up"></i></div>
            <div class="timeline-panel">
              <div class="timeline-heading">
                <h4 class="timeline-title">Pemira Fasilkom UI</h4>
              </div>
              <div class="timeline-body">
                <p></p>
              </div>
            </div>
          </li>
      </ul>
  </div>
  </div>
</div>
</section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/index.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/design.css' %}">

    <title>RAD</title>
  </head>
  <body class="mt-5">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
      <a class="navbar-brand" href="index.html">Raul Arrafi Delfarra</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'RAD:index' %}">About</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:experience' %}">Experience</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:education' %}">Education</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:skills' %}">Skills</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:contact' %}">Contact</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:Schedule' %}">Schedule</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:portofolio' %}">Portofolio</a>
        </div>
      </div>
      </div>
    </nav>

<section id="about" class="ganjil">
<div class="container-fluid">
  <div class="row">
    <div class="col text-center">
      <img src="{% static 'images/MyPhoto.jpg' %}" width="25%" class="img-thumbnail foto">
      <h1 class="display-4">Raul Arrafi Delfarra</h1>
    </div>
  </div>

  <div class="row">
    <div class="col text-center"> 
      <h2>About</h2>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-md-5 text-center">
    <p>I am an undergraduate student with a demonstrated history of working in the information technology and services industry organization. Skilled in Python (Programming Language), Java (Programming Language), Microsoft Excel, Microsoft Word, Microsoft Office, and Microsoft PowerPoint. I love doing sports, reading, watching film, eating, and playing FIFA.</p>
    </div>
  </div>
</div>
</section>




























    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

schedule/templates/schedule.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/design.css' %}">

    <title>RAD</title>
  </head>
  <body class="mt-5">
    <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary">
      <div class="container">
      <a class="navbar-brand" href="index.html">Raul Arrafi Delfarra</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href="{% url 'RAD:index' %}">About</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:experience' %}">Experience</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:education' %}">Education</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:skills' %}">Skills</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:contact' %}">Contact</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:Schedule' %}">Schedule</a>
          <a class="nav-item nav-link active" href="{% url 'RAD:portofolio' %}">Portofolio</a>
        </div>
      </div>
      </div>
    </nav>

<section id="schedule" class="ganjil">
<div class="container-fluid">
  <div class="row">
    <div class="col">
      <form action='' method="POST">
        {% csrf_token %}
        {{ form }}
        <div class="centre-items">
        <input type="submit" class="btn btn-primary" value="Add Schedule">
        </div>
      </form>
    </div>
  </div>
</div>

<div class="row">
<div class="col">
  <table class="table">
    <thead>
      <tr>
      <th scope="col">Day</th>
      <th scope="col">Date</th>
      <th scope="col">Time</th>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Location</th>
      <th scope="col">Delete</th>
      </tr>
    </thead>
    <tbody>
      {% for jadwal in sched %}
        <tr>
        <th scope="row">{{jadwal.Day}}</th>
        <td>{{jadwal.Date}}</td>
        <td>{{jadwal.Time}}</td>
        <td>{{jadwal.Name}}</td>
        <td>{{jadwal.Category}}</td>
        <td>{{jadwal.Location}}</td>
        <td><a href="{% url 'RAD:Delete' pk=jadwal.pk %}"><button class="btn btn-icon btn-danger"><i class="fa fa-trash"></i></button></a></td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
</section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>